name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          activate-environment: dask-glm

      - name: Install dask_glm
        shell: bash -l {0}
        run: pip install -e .

      - name: Run flake8
        shell: bash -l {0}
        run: flake8 dask_glm

      - name: Run pytest
        shell: bash -l {0}
        run: pytest dask_glm
