name: Build and maybe upload to PyPI

on:
  push:
  pull_request:
  release:
    types:
      - released
      - prereleased

jobs:
  artifacts:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Build wheels
        run: pip wheel . -w dist
      - name: Build Source Dist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: ./dist/dask_glm*
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: ./dist/dask-glm*

  list_artifacts:
    name: List build artifacts
    needs: [artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: wheel
          path: dist
      - name: test
        run: |
          ls
          ls dist

  upload_pypi:
    needs: [artifacts]
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    environment:
      name: releases
      url: https://pypi.org/p/dask-glm
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: wheel
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
